### ISSUE TITLE
Upload extremely slow and no debug information for upload

### ISSUE THREAD

**Issue by agowa338** [cloudflare/utahfs#28]
I now gave utahfs another shot and I noticed the following two drawbacks:
1. For some reason it is very slow when uploading a 129MB file (it took over 5 hours for the first 70MB) to the s3 bucket at Backblaze (I'm using the generic s3 api not the specific backblaze one).
2. Even when utahfs-client is started with `-v` it doesn't show any information about the upload to the backend server.

The VPS is over at Hetzner and the S3 is at Backblaze.
I've started it with `utahfs-client -cfg ./utahfs.yaml -mount ./utahfs -v` and this configuration file (credentials changed)
```
storage-provider:
  s3-app-id: 2ce35e922f464cee961f17636c
  s3-app-key: f21ecb9b119a4437ac236478a7c80b02
  s3-bucket: c026f6e2-a8e6-40b7-aa62-8e58a2b112aa
  s3-url: https://s3.us-west-002.backblazeb2.com
  s3-region: us-west-002
keep-metadata: true
password: ioN8Dgr7WtDuF8g5efpWWBpcOHBWOjGsVzKTDf4B0abognzBp2xTEM2aBbbEYqFqMnhqxk7zrQK8E7rBky1BhKz1BymvIXgzMY1AE4X3YpUihc6SUeF6OEv3
```

Edit: Now additional two hours later it finally finished uploading the 129MB file.
